variables:
  HOST: "w00f0a21.kasserver.com"
  USERNAME: "w00f0a21"
  PASSWORD: "TQxKtFG8"
  DEPLOYMENT_PATH: "./scheunenhausamsee.de"

deploy:
  script:
    - apt-get update -qq && apt-get install -y -qq lftp
    - lftp -c "set ftp:ssl-allow no; open -u $USERNAME,$PASSWORD $HOST; mirror -Rnev ./ $DEPLOYMENT_PATH --ignore-time --parallel=10 --exclude-glob .git* --exclude .git/ .idea/"
  only:
    - master
